### ISSUE TITLE
#Ask Voice

### ISSUE THREAD

**Issue by zakirkun** [veldanava/Zetaaa#2]
Why the voice when i run, not like a woman voice?

**Comment by veldanava** [comment]
try to change volume value from 0 to another number, but default voices is female sound

**Comment by zakirkun** [comment]
yeah, im try it but vocie female not like zeta :(

**Comment by veldanava** [comment]
wtf mannn ^o^

**Comment by veldanava** [comment]
thx for opening the issue ^v^
